version: '3'

php:
  build: .
  ports:
   - "80:80"
   - "433:443"
  volumes:
   - ../www:/var/www/html
   - ./php-ini/php.ini:/usr/local/etc/php/conf.d/php.ini
  links:
   - db
  stdin_open: true
  tty: true
db:
  image: mysql:5.7
  container_name: mysql
  command: mysqld --sql_mode=""
  volumes:
   - ../db:/var/lib/mysql
  environment:
      - MYSQL_ROOT_PASSWORD: rootpasswd
      - MYSQL_DATABASE: mysql
      - MYSQL_USER: admin
      - MYSQL_PASSWORD: admin123
  ports:
    - "9906:3306"
app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 6080:80
    environment:
      - PMA_ARBITRARY=1